#!/usr/bin/env bash
set -e

# Default Variables
# ---
DEFAULT_USERNAME="csidecar"
DEFAULT_CONFIG_DIRECTORY="/etc/${DEFAULT_USERNAME}/casper-event-sidecar"
DEFAULT_DATA_DIRECTORY="/var/lib/${DEFAULT_USERNAME}/casper-event-sidecar"

# User Creation
# ---
# Assure DEFAULT_USERNAME user exists
if id -u ${DEFAULT_USERNAME} >/dev/null 2>&1; then
    echo "User ${DEFAULT_USERNAME} already exists."
else
    adduser --no-create-home --group --system ${DEFAULT_USERNAME}
fi

# Take ownership of directories and files installed
chown -R ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_DATA_DIRECTORY}
chown -R ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_CONFIG_DIRECTORY}

# This is required for replacement to insert scripts for systemd by cargo-deb
#DEBHELPER#