[workspace]
resolver = "3"
members = [
    "event_sidecar",
    "json_rpc",
    "listener",
    "metrics",
    "rpc_sidecar",
    "sidecar",
    "types",
]

[workspace.dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
casper-types = { version = "6.0.1", features = [
    "json-schema",
    "std",
] }
casper-binary-port = { version = "1.2.0" }
casper-event-listener = { path = "./listener", version = "2" }
casper-event-sidecar = { path = "./event_sidecar", version = "2" }
casper-event-types = { path = "./types", version = "2" }
casper-rpc-sidecar = { path = "./rpc_sidecar", version = "2" }
casper-json-rpc = { path = "./json_rpc", version = "2" }
datasize = "0.2"
derive-new = "0.7"
futures = "0"
futures-util = "0.3"
governor = { version = "0.10", default-features = false, features = [
    "dashmap",
    "std",
] }
itertools = "0.14"
jsonschema = "0.30"
metrics = { path = "./metrics", version = "2" }
rand = "0.8"
serde = { version = "1", default-features = false }
thiserror = "2"
tokio = "1"
toml = "0.8"
tracing = { version = "0", default-features = false }
tracing-subscriber = "0"
warp = { version = "0.3" }

[patch.crates-io]
casper-binary-port = { git = "https://github.com/casper-network/casper-node", branch = "feat-2.1" }
casper-types = { git = "https://github.com/casper-network/casper-node", branch = "feat-2.1" }