[package]
name = "casper-event-types"
version = "1.0.4"
edition = "2024"
description = "Types for casper-event-listener library"
license-file = "../LICENSE"
documentation = "README.md"
homepage = "https://github.com/casper-network/casper-sidecar/"
repository = "https://github.com/casper-network/casper-sidecar/"

[dependencies]
casper-types = { workspace = true }
mockall = "0.13"
once_cell = "1.21"
pretty_assertions = "1.4"
rand = { workspace = true, optional = true }
serde = { workspace = true, default-features = true, features = [
    "derive",
    "rc",
] }
serde_json = { version = "1.0", default-features = false, features = [
    "alloc",
    "raw_value",
] }
thiserror = { workspace = true }

[features]
sse-data-testing = ["casper-types/testing", "rand"]
additional-metrics = []

[dev-dependencies]
casper-types = { workspace = true, features = ["testing"] }
rand = { workspace = true }
