/// This struct holds flags that steer DDL generation for specific databases.
pub struct DatabaseSpecificConfiguration {
    /// For postgresql we need to use bigserial as autogenerated id which. Bigserial is generated by sea query when a combination of `big_integer`, `primary_key` and `autoincrement` is used.
    /// For sqlite we can't use `big_integer` becasue the ddl creation fails -> `big_integer` can't be combined with `autoincrement` in sqlite. Hence we need a way to know that for some databases we want to use `big_integer` and for some `integer` for autoincremented id definition.
    pub is_big_integer_id: bool,
    /// Postgresql doesn't support unsigned integers, so for some fields we need to be mindful of the fact that in postgres we might need to use a bigger type to accomodate scope of field
    pub db_supports_unsigned: bool,
}
